# Generated by Django 4.0.6 on 2022-07-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='cars_brand',
            new_name='car_brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='cars_model',
            new_name='car_model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='cars_vin',
            new_name='car_vin',
        ),
    ]
