# Generated by Django 4.0.6 on 2022-07-25 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_cars_car_rename_cars_brand_car_car_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_brand',
        ),
        migrations.AddField(
            model_name='car',
            name='car_maker',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_vin',
            field=models.CharField(error_messages={'unique': 'This car VIN already exists.'}, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, 'The car VIN has a 17 characters format!'), django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'The car VIN has only letters and numbers!')]),
        ),
    ]
