# Generated by Django 4.0.6 on 2022-07-25 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_car_brand_car_car_maker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 17, 24, 11, 694100), verbose_name='Date Added'),
        ),
    ]
