# Generated by Django 4.0.6 on 2022-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
