# Generated by Django 4.1 on 2022-08-17 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(default='', error_messages={'unique': 'This car VIN already exists.'}, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, 'The car VIN has a 17 characters format!'), django.core.validators.RegexValidator('^[A-Z0-9]*$', 'The car VIN has only numbers and capital letters!')])),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('described', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('short_title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=500)),
                ('year', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1900)])),
                ('make', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('trim', models.CharField(default='', max_length=100)),
                ('mileage', models.PositiveIntegerField(null=True)),
                ('mileage_unit', models.CharField(default='', max_length=100)),
                ('transmission_type', models.CharField(default='', max_length=100)),
                ('fuel_type', models.CharField(default='', max_length=100)),
                ('body_style', models.CharField(default='', max_length=100)),
                ('drivetrain', models.CharField(default='', max_length=100)),
                ('interior_color', models.CharField(default='', max_length=100)),
                ('exterior_color', models.CharField(default='', max_length=100)),
                ('doors', models.PositiveSmallIntegerField(null=True)),
                ('cylinders', models.PositiveSmallIntegerField(null=True)),
                ('displacement', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('msrp', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('state_of_vehicle', models.CharField(default='', max_length=100)),
                ('grouped_exterior_color', models.CharField(default='', max_length=100)),
                ('grouped_interior_color', models.CharField(default='', max_length=100)),
                ('engine', models.CharField(default='', max_length=100)),
                ('fuel_economy_city', models.PositiveSmallIntegerField(null=True)),
                ('fuel_economy_city_unit', models.CharField(default='', max_length=100)),
                ('fuel_economy_highway', models.PositiveSmallIntegerField(null=True)),
                ('fuel_economy_highway_unit', models.CharField(default='', max_length=100)),
                ('availability', models.BooleanField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('normalized_make', models.CharField(default='', max_length=100)),
                ('grouped_body_style', models.CharField(default='', max_length=100)),
                ('grouped_transmission_type', models.CharField(default='', max_length=100)),
                ('sale_price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('url', models.URLField(null=True)),
                ('stock_number', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
