# Generated by Django 4.1 on 2022-08-17 15:25

import json
import os.path
from django.db import migrations, IntegrityError


def refresh_data(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    with open(os.path.abspath(os.path.join(os.sep, os.getcwd(), 'cars', 'files', 'cars', 'hutto.json'))) as json_file:
        vin_list = json.load(json_file)
    for vin in vin_list:
        try:
            Car.objects.create(vin=vin)
        except IntegrityError:
            return "Something went wrong. (IntegrityError)"


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(refresh_data),
    ]
