# Generated by Django 4.0.6 on 2022-07-26 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='body_style',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='car_trim',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='cylinders',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='No data.', max_length=500),
        ),
        migrations.AddField(
            model_name='car',
            name='displacement',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='drivetrain',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='exterior_color',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_economy_city',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_economy_city_unit',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_economy_highway',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_economy_highway_unit',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='grouped_body_style',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='grouped_exterior_color',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='grouped_interior_color',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='grouped_transmission_type',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(default='http://127.0.0.1:8000/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage_unit',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='msrp',
            field=models.FloatField(default=0, max_length=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='car',
            name='normalized_make',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='sale_price',
            field=models.FloatField(default=0, max_length=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='car',
            name='state_of_vehicle',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='stock_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(default='No data.', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(1900)]),
        ),
    ]
