# Generated by Django 4.0.6 on 2022-07-27 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_availability_car_body_style_car_car_trim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_vin',
            field=models.CharField(error_messages={'unique': 'This car VIN already exists.'}, max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17, 'The car VIN has a 17 characters format!'), django.core.validators.RegexValidator('^[A-Z0-9]*$', 'The car VIN has only numbers and capital letters!')]),
        ),
    ]
